// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "info": {
    "title": "User Service Inno Taxi",
    "version": "1.0"
  },
  "securityDefinitions": {
    "JWT": {
      "type": "apiKey",
      "in": "header",
      "name": "Authorization"
    }
  },
  "definitions": {
    "DTO.User": {
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DTO.GetUserResponse": {
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "Rating": {
          "type": "integer"
        },
        "phoneNumber": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DTO.LogInUserRequest": {
      "properties": {
        "phoneNumber": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DTO.ChangeUserRequest": {
      "properties": {
        "phoneNumber": {
          "type": "string"
        },
        "newPhoneNumber": {
          "type": "string"
        },
        "newEmail": {
          "type": "string"
        },
        "newName": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DTO.DeleteUserRequest": {
      "properties": {
        "id": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "id": {
      "type": "integer"
    },
    "token": {
      "type": "string"
    }
  },
  "paths": {
    "/api/v1/user": {
      "get": {
        "summary": "Respond info about user(phone number, email, name, rating). To get info you need token(to be authorized)",
        "security": [
          {
            "JWT": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "$ref": "#/definitions/DTO.GetUserResponse"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid token."
          }
        },
        "tags": [
          "Actions with token"
        ]
      },
      "put": {
        "description": "Update user info(). To update you need token(to be authorized)",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "JWT": []
          }
        ],
        "parameters": [
          {
            "name": "UpdateUser",
            "in": "body",
            "description": "object which you need send to update user data",
            "schema": {
              "$ref": "#/definitions/DTO.ChangeUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid data, which you put or invalid token."
          }
        },
        "summary": "Update user info",
        "tags": [
          "Actions with token"
        ]
      },
      "delete": {
        "summary": "Delete user. To delete user you need token(to be authorized)",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "JWT": []
          }
        ],
        "parameters": [
          {
            "name": "delete user request",
            "in": "body",
            "description": "object which you need send to delete yourself",
            "schema": {
              "$ref": "#/definitions/DTO.DeleteUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid id or token."
          }
        },
        "tags": [
          "Actions with token"
        ]
      }
    },
    "/api/v1/user/login": {
      "post": {
        "summary": "Log in user in system.",
        "parameters": [
          {
            "name": "log in request",
            "in": "body",
            "description": "object which you need send to login",
            "schema": {
              "$ref": "#/definitions/DTO.LogInUserRequest"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "$ref": "#/definitions/token"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be wrong password or absense of user."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/user/register": {
      "post": {
        "summary": "Register new user in system.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Register Request",
            "in": "body",
            "description": "object which you need send to register",
            "schema": {
              "$ref": "#/definitions/DTO.User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User created",
            "schema": {
              "items": {
                "$ref": "#/definitions/id"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid data."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/user/logout": {
      "get": {
        "summary": "Log out from system.",
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "JWT": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request. Cause can be log out before."
          },
          "500": {
            "description": "Internal server error."
          }
        },
        "tags": [
          "Actions with token"
        ]
      }
    }
  },
  "host": "localhost:8080",
  "swagger": "2.0"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
